environment:

  matrix:
    - PYTHON: "C:\\Python27"
    - PYTHON: "C:\\Python36"

init:
  - set PATH=%PYTHON%\Scripts;%PATH%

install:
  - "%PYTHON%\\python.exe -m pip install tox"

build: off

test_script:
  - tox

artifacts:
  - path: dist\*
